package com.securemessaging.entity;

public enum GroupDecisionCategory {
    ROUTINE_OPERATION,
    PROJECT_DIRECTION,
    TASK_ASSIGNMENT,
    SCHEDULING,
    FINANCIAL_COMMITMENT,
    MEMBERSHIP_ACTION,
    ADMIN_ROLE_CHANGE,
    GOVERNANCE_CHANGE,
    SECURITY_CHANGE,
    PRIVACY_CHANGE,
    DATA_RETENTION_CHANGE,
    EXTERNAL_SHARING,
    OWNERSHIP_TRANSFER,
    GROUP_DISSOLUTION,
    FOUNDATIONAL_CHANGE
}