services:
  postgres:
    image: postgres:17
    container_name: secure-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: secure_messaging
      POSTGRES_USER: secure_user
      POSTGRES_PASSWORD: secure_password
    volumes:
      - secure_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./secure-messaging-backend
    container_name: secure-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/secure_messaging
      SPRING_DATASOURCE_USERNAME: secure_user
      SPRING_DATASOURCE_PASSWORD: secure_password
      JWT_SECRET: securemessagingjwtsecretkeymustbeatleast32chars
    ports:
      - "8080:8080"

  frontend:
    build: ./secure-messaging-frontend
    container_name: secure-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  secure_pgdata:
