name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy app on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
           script: |
              cd /home/ec2-user/secure-messaging-platform
              git pull origin main

              docker compose down --rmi all --volumes --remove-orphans

              docker system prune -af

              rm -rf secure-messaging-frontend/dist

              docker compose build --no-cache

              docker compose up -d

              docker ps
          
