name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy app on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
           script: |
              cd /home/ec2-user/secure-messaging-platform
              git status
              git log --oneline -3
              git pull origin main
              grep -n "secure-messaging-logo" secure-messaging-frontend/src/pages/Register.js
              docker compose down
              rm -rf secure-messaging-frontend/dist
              docker compose build --no-cache
              docker compose up -d
              docker compose exec -T frontend sh -c "grep -R \"secure-messaging-logo\" /usr/share/nginx/html || true"
              docker compose exec -T frontend sh -c "grep -R \"Development test account\" /usr/share/nginx/html || true"
              docker ps
          
